### ISSUE TITLE
Environment not properly set when deploying

### ISSUE THREAD

**Issue by trevorrjohn** [pagefront/ember-pagefront#17]
When I am deploying to my staging (and presumably development) environment it is being deployed with the default environment of 'production'. Any thoughts on where I should be adding this?

**Comment by jasonkriss** [comment]
Sorry the bit you @trevorrjohn! This actually isn't a bug but rather a result of poor documentation. The issue is that there are two types of "environments" here that don't always align one-to-one. There are Pagefront environments (production, staging, development) and there are ember build environments (that happen to often coincide with Pagefront environments). The reason these have to be separate is that a lot of people want to deploy 'production' ember builds to their Pagefront staging environment.

If you want to deploy a staging ember build to Pagefront staging, you'll need to modify your config/deploy.js so it looks something like this:

``` javascript
module.exports = function(deployTarget) {  
  var ENV = {
    pagefront: {
      app: 'your_app_name',
      key: process.env.PAGEFRONT_KEY
    }
  };
  if (deployTarget === 'staging') {
    ENV.buildEnv = 'staging';
  }
  return ENV;
};
```

Let me know if that doesn't make sense. It's a lil confusing and I we definitely need to spell this out in a more obvious way in the docs. Sorry again for the trouble!

**Comment by trevorrjohn** [comment]
Hey @jasonkriss it doesn't appear to be working. I added that and am still seeing this in the deploy logs:

```
- validating config
- Missing config: `environment`, using default: `production`
```

**Comment by jasonkriss** [comment]
ahh yea that's outdated. Sorry! Try this...

``` javascript
module.exports = function(deployTarget) {
  return {
    build: {
      environment: deployTarget === 'staging' ? 'staging' : 'production',
    },

    pagefront: {
      app: 'your_app_name',
      key: process.env.PAGEFRONT_KEY
    }
  };
};
```

**Comment by trevorrjohn** [comment]
Thanks!

I think I am still a little confused about how to setup my environments properly.

Right now our `config/environment.js` looks like this:

``` javascript
module.exports = function(environment) {
    var ENV = {
        APP: {
            api_host: environment === 'production' ? 'https://prod.com' : 'https://staging.com'
        }
    }
    /* more stuff */
    return ENV;
}
```

What I really want to be looking at is the `deployTarget` not the environment. Can you think of a good way to do this?

**Comment by trevorrjohn** [comment]
This looks like the solution I was looking for: http://blog.firstiwaslike.com/staging-environments-with-ember-cli-deploy/

**Comment by jasonkriss** [comment]
@trevorrjohn good find! That looks like a good way to solve it. Let me know if you have any other questions though.

**Comment by stevenwu** [comment]
@jasonkriss is it possible to do `ember deploy staging` and have it deploy to `https://myapp.pagefrontapp.com` instead of `https://myapp.staging.pagefrontapp.com`?

My use case is that I have separate pagefront apps for staging and production. I've tried

```
if (deployTarget === 'staging') {
    ENV.build.environment = 'development';
}
```

and

```
if (deployTarget === 'staging') {
    ENV.buildEnv = 'staging';
}
```

**Comment by jasonkriss** [comment]
@stevenwu This is actually quite challenging to do with the current setup. Can I ask, why you have separate pagefront apps? I jus wanna see if there is another way we can accomplish what you want to do and I also would like to figure out if this is something that we should add explicit support for.

**Comment by stevenwu** [comment]
@jasonkriss there isn't a good reason for it, that's just how it was setup 😄  It's good to know that it isn't actually possible. Thanks.
